// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMRCtmywZZ6zsuo78exsXIq3DyjnpUNuI',
    appId: '1:363622380219:web:226f997b670c49a42baf9e',
    messagingSenderId: '363622380219',
    projectId: 'io-extended-gdg-la-paz',
    authDomain: 'io-extended-gdg-la-paz.firebaseapp.com',
    storageBucket: 'io-extended-gdg-la-paz.appspot.com',
    measurementId: 'G-MFZTTT5F4D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4vL-vWvZvvSfRzyUIUWzUh98FcOEN_so',
    appId: '1:363622380219:android:ca0a0530fed5909e2baf9e',
    messagingSenderId: '363622380219',
    projectId: 'io-extended-gdg-la-paz',
    storageBucket: 'io-extended-gdg-la-paz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKgJB-fggaMoRL3t6J_7bwz3zBhdjsS_E',
    appId: '1:363622380219:ios:42e62487f1e5ec722baf9e',
    messagingSenderId: '363622380219',
    projectId: 'io-extended-gdg-la-paz',
    storageBucket: 'io-extended-gdg-la-paz.appspot.com',
    iosClientId: '363622380219-prgukie4etfjbcovmoqsmua4k7ltt1gn.apps.googleusercontent.com',
    iosBundleId: 'com.example.ioExtended2023GdgLaPaz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKgJB-fggaMoRL3t6J_7bwz3zBhdjsS_E',
    appId: '1:363622380219:ios:28c61ef3278ea0ca2baf9e',
    messagingSenderId: '363622380219',
    projectId: 'io-extended-gdg-la-paz',
    storageBucket: 'io-extended-gdg-la-paz.appspot.com',
    iosClientId: '363622380219-5mhamgpd9eu6i4o74lkn2srdl86buq39.apps.googleusercontent.com',
    iosBundleId: 'com.example.ioExtended2023GdgLaPaz.RunnerTests',
  );
}
